### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by shannu1119** [maniiiisha/FoodDeliveryTimePrediction#1]
How to run and excute the project can u explain in detail please

**Comment by maniiiisha** [comment]
Hi, to run the code you need to run the application.py file using the command 'python application.py'. And to access the flask application run 'http://127.0.0.1:5000/' in your browser.

**Comment by shannu1119** [comment]
Actually I am searching for final year project.
Can you please say the step by step process from starting i.e from setup to run the code

**Comment by maniiiisha** [comment]
please share your email id or linkedin, i’ll get back to you asap.

**Comment by shannu1119** [comment]
mail : shanmukshanmuk19@gmail.com
linkedin : https://www.linkedin.com/in/shanmuk-avupati/
